# Generated by Django 5.0 on 2024-03-13 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_devicesmodel_employeemodel_devicesreturnedmodel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicesmodel',
            name='description',
            field=models.TextField(),
        ),
    ]
