# Generated by Django 5.0 on 2024-03-13 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_devicesmodel_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicesassignmodel',
            name='device_condition',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='devicesreturnedmodel',
            name='device_condition',
            field=models.TextField(),
        ),
    ]
